name: Fetch latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 */12 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Use Node.js v14.15.4
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'

    - name: Install dependencies
      run: npm install

    - name: Fetch latest data
      run: npm run prestart

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ=UTC-9 date "+%Y/%m/%d %H:%M:%S")
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
